# Generated by Django 4.1 on 2024-03-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="pv",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="post",
            name="uv",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
