# Generated by Django 4.1 on 2024-04-07 02:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_post_comment_html"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="comment_html",
            new_name="content_html",
        ),
    ]
